import type { Mii } from './types';

export const initialMiis: Mii[] = [
  {
    id: '1',
    name: 'Luna',
    skinTone: '#FDDBB4',
    hairColor: '#3B1F0A',
    shirtColor: '#7EC8E3',
    mood: 'happy',
    happiness: 82,
    activity: 'reading by the window',
    friends: ['2', '4'],
  },
  {
    id: '2',
    name: 'Marco',
    skinTone: '#C68642',
    hairColor: '#1A1A1A',
    shirtColor: '#A8D8A8',
    mood: 'content',
    happiness: 75,
    activity: 'napping on the couch',
    friends: ['1', '3'],
  },
  {
    id: '3',
    name: 'Yuki',
    skinTone: '#F5CBA7',
    hairColor: '#2C2C2C',
    shirtColor: '#FFB7C5',
    mood: 'sleepy',
    happiness: 60,
    activity: 'making tea',
    friends: ['2', '5'],
  },
  {
    id: '4',
    name: 'Bram',
    skinTone: '#D2955A',
    hairColor: '#5C3D1E',
    shirtColor: '#C3A6FF',
    mood: 'bored',
    happiness: 55,
    activity: 'staring out the window',
    friends: ['1', '5'],
  },
  {
    id: '5',
    name: 'Cleo',
    skinTone: '#8D5524',
    hairColor: '#1A0A00',
    shirtColor: '#FFD580',
    mood: 'hungry',
    happiness: 68,
    activity: 'looking for snacks',
    friends: ['3', '4'],
  },
];

export const eventTemplates = [
  { text: '{name} made a really good sandwich.', emoji: '🥪' },
  { text: '{name} watched the sunset from the balcony.', emoji: '🌅' },
  { text: '{name} found a book they forgot they had.', emoji: '📖' },
  { text: '{name} took a really long nap.', emoji: '😴' },
  { text: '{name} reorganized their sock drawer. Very satisfying.', emoji: '🧦' },
  { text: '{name} hummed a song they couldn\'t quite remember.', emoji: '🎵' },
  { text: '{name} made a cup of tea and it was perfect.', emoji: '🍵' },
  { text: '{name} watered the plants and felt good about it.', emoji: '🌿' },
  { text: '{name} found the perfect sitting position on the couch.', emoji: '🛋️' },
  { text: '{name} said hi to a bird outside.', emoji: '🐦' },
  { text: '{name} tried a new flavor of chips. Verdict: pretty good.', emoji: '🍟' },
  { text: '{name} wrote in their journal for the first time in months.', emoji: '📓' },
  { text: '{name} did a small stretch and it cracked nicely.', emoji: '🧘' },
  { text: '{name} lit a candle and felt very cozy.', emoji: '🕯️' },
  { text: '{name} watched a documentary about penguins.', emoji: '🐧' },
  { text: '{name} baked cookies and shared some with {friend}.', emoji: '🍪' },
  { text: '{name} and {friend} sat in comfortable silence.', emoji: '🌙' },
  { text: '{name} went on a slow walk around the island.', emoji: '🚶' },
  { text: '{name} organized their bookshelf by color.', emoji: '📚' },
  { text: '{name} took a bubble bath and felt completely restored.', emoji: '🛁' },
  { text: '{name} sent {friend} a nice message out of nowhere.', emoji: '💌' },
  { text: '{name} watched clouds for a while.', emoji: '☁️' },
  { text: '{name} made soup from scratch.', emoji: '🍲' },
  { text: '{name} fell asleep to the sound of rain.', emoji: '🌧️' },
  { text: '{name} found a smooth rock and kept it.', emoji: '🪨' },
];
